FROM node:22-alpine3.19 AS build
WORKDIR /app
COPY api/package*.json .
RUN npm i
COPY api/* .
RUN npm run build

#Production stage
FROM node:22-alpine3.19 AS production
WORKDIR /app
COPY api/package*.json .
RUN npm ci --only=production
COPY --from=build /app/dist ./dist
CMD ["node", "dist/index.js"]